title: "Yeye Jin â€“ Data Analysis Portfolio"
description: "Projects, data sources, and visualizations for my data analysis class."

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
